# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: dispatch

on:
  workflow_dispatch:
    inputs:
      voi:
        description: 'List of voivodeships'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Run ${{ github.event.inputs.voi}}
      env:
        PAT: ${{ secrets.PAT }}
        EREJ_PID_PLUTA: ${{ secrets.EREJ_PID_PLUTA }}
        EREJ_SID: ${{ secrets.EREJ_SID_1 }}
        EREJ_CSRF: ${{ secrets.EREJ_CSRF_1 }}
      run: ./pusher.sh ${{ github.event.inputs.voi}}
